package server
import "net/http"
func(s *Server)dashboard(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","text/html; charset=utf-8");w.Write([]byte(dashHTML))}
const dashHTML=`<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Scout</title>
<style>:root{--bg:#1a1410;--bg2:#241e18;--bg3:#2e261e;--rust:#c45d2c;--rl:#e8753a;--leather:#a0845c;--cream:#f0e6d3;--cd:#bfb5a3;--cm:#7a7060;--gold:#d4a843;--green:#4a9e5c;--red:#c44040;--mono:'JetBrains Mono',Consolas,monospace;--serif:'Libre Baskerville',Georgia,serif}*{margin:0;padding:0;box-sizing:border-box}body{background:var(--bg);color:var(--cream);font-family:var(--mono);font-size:13px;line-height:1.6}.hdr{padding:.6rem 1.2rem;border-bottom:1px solid var(--bg3);display:flex;justify-content:space-between;align-items:center}.hdr h1{font-family:var(--serif);font-size:1rem}.hdr h1 span{color:var(--rl)}.main{max-width:700px;margin:0 auto;padding:1rem}.btn{font-family:var(--mono);font-size:.68rem;padding:.3rem .6rem;border:1px solid;cursor:pointer;background:transparent}.btn-p{border-color:var(--rust);color:var(--rl)}.btn-p:hover{background:var(--rust);color:var(--cream)}.scan{background:var(--bg2);border:1px solid var(--bg3);padding:.6rem;margin-bottom:.4rem}.scan h3{font-size:.82rem;margin-bottom:.15rem}.scan-meta{font-size:.65rem;color:var(--cm);display:flex;gap:.7rem}.scan-stat{font-size:.7rem;display:flex;gap:.8rem;margin-top:.3rem}.empty{text-align:center;padding:2rem;color:var(--cm);font-style:italic;font-family:var(--serif)}.modal-bg{position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.65);display:flex;align-items:center;justify-content:center;z-index:100}.modal{background:var(--bg2);border:1px solid var(--bg3);padding:1.5rem;width:90%;max-width:450px}.modal h2{font-family:var(--serif);font-size:.9rem;margin-bottom:1rem}label.fl{display:block;font-size:.65rem;color:var(--leather);text-transform:uppercase;letter-spacing:1px;margin-bottom:.2rem;margin-top:.5rem}input[type=text],input[type=number],select{background:var(--bg);border:1px solid var(--bg3);color:var(--cream);padding:.35rem .5rem;font-family:var(--mono);font-size:.78rem;width:100%;outline:none}</style>
<link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital@0;1&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">
</head><body><div class="hdr"><h1><span>Scout</span></h1><button class="btn btn-p" onclick="showNew()">+ Scan</button></div>
<div class="main"><div id="list"></div></div><div id="modal"></div>
<script>
async function api(u,o){return(await fetch(u,o)).json()}
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function timeAgo(d){if(!d)return'';const s=Math.floor((Date.now()-new Date(d))/1e3);if(s<60)return s+'s ago';if(s<3600)return Math.floor(s/60)+'m ago';return Math.floor(s/3600)+'h ago'}
async function load(){const d=await api('/api/scans');const scans=d.scans||[];
document.getElementById('list').innerHTML=scans.length?scans.map(s=>'<div class="scan"><h3>'+esc(s.project)+(s.ecosystem?' <span style="font-size:.65rem;color:var(--cm)">'+esc(s.ecosystem)+'</span>':'')+'</h3><div class="scan-meta"><span style="color:'+(s.status==='done'?'var(--green)':'var(--gold)')+'">'+s.status+'</span><span>'+timeAgo(s.created_at)+'</span></div><div class="scan-stat"><span>'+s.total_deps+' deps</span><span style="color:'+(s.outdated?'var(--gold)':'var(--green)')+'">'+s.outdated+' outdated</span><span style="color:'+(s.vulnerable?'var(--red)':'var(--green)')+'">'+s.vulnerable+' vulnerable</span></div></div>').join(''):'<div class="empty">No scans yet.</div>'}
function showNew(){document.getElementById('modal').innerHTML='<div class="modal-bg" onclick="if(event.target===this)closeModal()"><div class="modal"><h2>New Scan</h2><label class="fl">Project</label><input type="text" id="ns-proj" placeholder="my-app"><label class="fl">Ecosystem</label><input type="text" id="ns-eco" placeholder="npm, go, pip"><label class="fl">Total Dependencies</label><input type="number" id="ns-deps" value="0"><label class="fl">Outdated</label><input type="number" id="ns-out" value="0"><label class="fl">Vulnerable</label><input type="number" id="ns-vul" value="0"><div style="display:flex;gap:.5rem;margin-top:1rem"><button class="btn btn-p" onclick="save()">Save</button><button class="btn" style="border-color:var(--bg3);color:var(--cm)" onclick="closeModal()">Cancel</button></div></div></div>'}
async function save(){const b={project:document.getElementById('ns-proj').value,ecosystem:document.getElementById('ns-eco').value,status:'done',total_deps:parseInt(document.getElementById('ns-deps').value)||0,outdated:parseInt(document.getElementById('ns-out').value)||0,vulnerable:parseInt(document.getElementById('ns-vul').value)||0};if(!b.project){alert('Project required');return};await api('/api/scans',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});closeModal();load()}
function closeModal(){document.getElementById('modal').innerHTML=''}
load()
</script></body></html>`
