package server

var dashboardHTML = []byte(`<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Stockyard Scout</title><style>:root{--bg:#1a1410;--surface:#241c15;--border:#3d2e1e;--rust:#c4622d;--leather:#8b5e3c;--cream:#f5e6c8;--muted:#7a6550;--text:#e8d5b0}*{box-sizing:border-box;margin:0;padding:0}body{background:var(--bg);color:var(--text);font-family:'JetBrains Mono',monospace,sans-serif;min-height:100vh}header{background:var(--surface);border-bottom:1px solid var(--border);padding:1rem 2rem;display:flex;align-items:center;gap:1rem}.logo{color:var(--rust);font-size:1.25rem;font-weight:700}.badge{background:var(--rust);color:var(--cream);font-size:0.65rem;padding:0.2rem 0.5rem;border-radius:3px;font-weight:600;text-transform:uppercase}main{max-width:1100px;margin:0 auto;padding:2rem}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem;margin-bottom:2rem}.stat{background:var(--surface);border:1px solid var(--border);border-radius:6px;padding:1.25rem;text-align:center}.stat-value{font-size:1.75rem;font-weight:700;color:var(--rust)}.stat-label{font-size:0.75rem;color:var(--muted);margin-top:0.25rem;text-transform:uppercase;letter-spacing:0.05em}.grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.card{background:var(--surface);border:1px solid var(--border);border-radius:6px;padding:1.5rem}.card h2{font-size:0.85rem;color:var(--muted);text-transform:uppercase;letter-spacing:0.08em;margin-bottom:1rem}.form-row{display:flex;gap:0.5rem;margin-bottom:0.75rem;flex-wrap:wrap;align-items:flex-start}select,input,textarea{background:var(--bg);border:1px solid var(--border);color:var(--text);padding:0.5rem 0.75rem;border-radius:4px;font-family:inherit;font-size:0.85rem}.form-row select,.form-row input{flex:1}textarea{width:100%;min-height:80px;resize:vertical}.btn{background:var(--rust);color:var(--cream);border:none;padding:0.5rem 1rem;border-radius:4px;cursor:pointer;font-family:inherit;font-size:0.85rem;font-weight:600}.btn:hover{opacity:0.85}.btn-sm{padding:0.25rem 0.6rem;font-size:0.75rem}.btn-danger{background:#7a2020}table{width:100%;border-collapse:collapse;font-size:0.82rem}th{text-align:left;color:var(--muted);padding:0.5rem;border-bottom:1px solid var(--border);font-size:0.75rem;text-transform:uppercase}td{padding:0.5rem;border-bottom:1px solid var(--border)}.empty{color:var(--muted);font-size:0.85rem;padding:1rem 0;text-align:center}.full{grid-column:1/-1}.badge-g{background:#1a3a1a;color:#5cb85c;border:1px solid #2d5a2d;border-radius:3px;padding:0.1rem 0.4rem;font-size:0.72rem}.badge-r{background:#3a1a1a;color:#d9534f;border:1px solid #5a2d2d;border-radius:3px;padding:0.1rem 0.4rem;font-size:0.72rem}.badge-y{background:#3a2f1a;color:#f0ad4e;border:1px solid #5a4a2d;border-radius:3px;padding:0.1rem 0.4rem;font-size:0.72rem}</style></head>
<body>
<header><span class="logo">&#x2B21; Stockyard</span><span style="color:var(--muted)">/</span><span style="color:var(--cream);font-weight:600">Scout</span><span class="badge">Link Checker</span></header>
<main><div class="stats"><div class="stat"><div class="stat-value" id="s1">0</div><div class="stat-label">Sites</div></div><div class="stat"><div class="stat-value" id="s2">0</div><div class="stat-label">Issues</div></div><div class="stat"><div class="stat-value" id="s3">FREE</div><div class="stat-label">Tier</div></div></div><div class="grid">
<div class="card"><h2>Add Site</h2><div class="form-row"><input id="f-name" placeholder="My Site"></div><div class="form-row"><input id="f-url" placeholder="https://example.com"></div><div class="form-row"><select id="f-sched"><option value="daily">Daily</option><option value="weekly">Weekly</option></select></div><button class="btn" onclick="createSite()">Add Site</button></div>
<div class="card full"><h2>Sites</h2><table><thead><tr><th>Name</th><th>URL</th><th>Schedule</th><th>Last Crawl</th><th></th></tr></thead><tbody id="sites-body"><tr><td colspan="5" class="empty">No sites</td></tr></tbody></table></div>
<div class="card full" id="runs-card" style="display:none"><h2>Crawl Runs</h2><table><thead><tr><th>Started</th><th>Pages</th><th>Broken</th><th>SSL</th><th>Status</th><th></th></tr></thead><tbody id="runs-body"></tbody></table></div>
<div class="card full" id="issues-card" style="display:none"><h2>Issues</h2><table><thead><tr><th>URL</th><th>Type</th><th>Code</th><th>Detail</th></tr></thead><tbody id="issues-body"></tbody></table></div>
</div></main>
<script>
async function api(m,p,bd){var o={method:m,headers:{"Content-Type":"application/json"}};if(bd)o.body=JSON.stringify(bd);var r=await fetch(p,o);return r.json();}
async function loadStats(k1,k2,k3){var s=await api("GET","/api/stats");var l=await api("GET","/api/limits");if(k1)document.getElementById("s1").textContent=s[k1]||0;if(k2)document.getElementById("s2").textContent=s[k2]||0;document.getElementById("s3").textContent=(l.tier||"free").toUpperCase();}
async function load(){loadStats("sites","issues");loadSites();}
async function loadSites(){var data=await api("GET","/api/sites");var tbody=document.getElementById("sites-body");if(!data||!data.length){tbody.innerHTML="<tr><td colspan='5' class='empty'>No sites</td></tr>";return;}tbody.innerHTML=data.map(function(s){return "<tr><td style='color:var(--cream)'>"+s.name+"</td><td style='color:var(--leather);font-size:0.8rem'>"+s.base_url+"</td><td>"+s.schedule+"</td><td style='font-size:0.75rem;color:var(--muted)'>"+(s.last_crawl_at?new Date(s.last_crawl_at).toLocaleDateString():"Never")+"</td><td style='display:flex;gap:0.5rem'><button class='btn btn-sm' onclick='crawlSite("+s.id+")'>Crawl</button><button class='btn btn-sm' onclick='showRuns("+s.id+")'>Runs</button><button class='btn btn-sm btn-danger' onclick='deleteSite("+s.id+")'>Del</button></td></tr>";}).join("");}
async function crawlSite(id){var res=await api("POST","/api/sites/"+id+"/crawl");if(res.error){alert(res.error);return;}alert(res.message);setTimeout(load,1000);}
async function showRuns(id){var data=await api("GET","/api/sites/"+id+"/runs");document.getElementById("runs-card").style.display="block";var tbody=document.getElementById("runs-body");if(!data||!data.length){tbody.innerHTML="<tr><td colspan='6' class='empty'>No runs</td></tr>";return;}tbody.innerHTML=data.map(function(r){return "<tr><td style='font-size:0.8rem'>"+new Date(r.started_at).toLocaleString()+"</td><td>"+r.pages_checked+"</td><td style='color:"+(r.broken_links>0?"#d9534f":"#5cb85c")+"'>"+r.broken_links+"</td><td>"+r.ssl_issues+"</td><td><span class='badge-"+(r.status==="done"?"g":"y")+"'>"+r.status+"</span></td><td><button class='btn btn-sm' onclick='showIssues("+r.id+")'>Issues</button></td></tr>";}).join("");}
async function showIssues(id){var data=await api("GET","/api/runs/"+id+"/issues");document.getElementById("issues-card").style.display="block";var tbody=document.getElementById("issues-body");if(!data||!data.length){tbody.innerHTML="<tr><td colspan='4' class='empty'>No issues found</td></tr>";return;}tbody.innerHTML=data.map(function(i){return "<tr><td style='font-size:0.8rem;word-break:break-all;color:var(--leather)'>"+i.url+"</td><td><span class='badge-r'>"+i.issue_type+"</span></td><td>"+i.status_code+"</td><td style='font-size:0.75rem;color:var(--muted)'>"+i.detail+"</td></tr>";}).join("");}
async function createSite(){var s={name:document.getElementById("f-name").value.trim(),base_url:document.getElementById("f-url").value.trim(),schedule:document.getElementById("f-sched").value};if(!s.base_url){alert("URL required");return;}var res=await api("POST","/api/sites",s);if(res.error){alert(res.error);return;}document.getElementById("f-url").value="";document.getElementById("f-name").value="";load();}
async function deleteSite(id){if(!confirm("Delete site?"))return;await api("DELETE","/api/sites/"+id);load();}
load();
</script></body></html>`)
